# Generated by Django 4.0.2 on 2022-02-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Emp_Code', models.CharField(max_length=50)),
                ('Moblie', models.CharField(max_length=50)),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeReg.position')),
            ],
        ),
    ]
